spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Notification?serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  mail:
    host: localhost
    port: 1025
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: Notification-service
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8050
feign:
  client:
    config:
      userClient:
        url: http://localhost:8090