spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  web:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      allow-credentials: true

  mail:
    host: localhost
    port: 1025
  kafka:
    producer:
      value-serializer=com:
        pfe:
          projet:
            Reunions:
              ReunionConfirmationSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/reunions?serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: reunions-service
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8010
